### ISSUE TITLE
Model for GET and POST are not the same in WikiItemApi items.py file

### ISSUE THREAD

**Issue by KetchupOnMyKetchup** [razi-rais/blockchain#1]
Can you synchronize the models so that the GET and POST would use the same model?

**Comment by KetchupOnMyKetchup** [comment]
When the Angular front end code has GET/POST there is a model that is being used and it would be easier to GET and PUSH to the backend assuming the model is the same.

**Comment by razi-rais** [comment]
This issue was moved to razi-rais/eth-wikipedia-changetracker#1
